### ISSUE TITLE
Appliquer un filtre pour adoucir les changements de distance

### ISSUE THREAD

**Issue by rouvoy** [HubHouse-Lille/GeokH-app#1]
Pour éviter les «sauts» entre 2 valeurs calculées pour la distance à la balise, il est possible de lisser la nouvelle valeur en intégrant la précédente valeur: `int distance = 0.5 * nouvelle_distance + 0.5 * distance`

**Comment by MickaelMatuchak** [comment]
Fonctionnalité intégrée au pull request #9.
