### ISSUE TITLE
Appliquer un filtre pour adoucir les changements de direction

### ISSUE THREAD

**Issue by rouvoy** [HubHouse-Lille/GeokH-app#2]
Pour éviter les «sauts» entre 2 valeurs calculées pour l'orientation à la balise, il est possible de lisser la nouvelle valeur en intégrant la précédente valeur: `int orientation = 0.5 * nouvelle_ orientation + 0.5 * orientation`

**Comment by MickaelMatuchak** [comment]
Fonctionnalité intégrée au pull request #9.
